name: ovanet
channels:
  - pytorch
dependencies:
  - python=3.6.9
  - cudatoolkit=11.0
  - pytorch=1.7.0
  - torchvision=0.8.0
  - torchaudio=0.7.0
  - pip
  - pip:
    - packaging
    - pyyaml
    - easydict
    - scikit-learn